#!/usr/bin/env bash
# This script copies a file from local machine to webserver

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp "$1" "$3@$2":~/
else
	scp -i "$4"  "$1" "$3@$2":~/
fi
