#!/usr/bin/env bash
# This Configures a new ubuntu machine by installing

# Check if nginx is install
sudo apt -y update
# install nginex
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
