#!/usr/bin/env bash
# This Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
#echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx start
