#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# This edit config file
server_config=\
"
frontend  maydan-frontend
        bind *:80
        mode http
        default_backend maydan-backend
backend maydan-backend
        balance roundrobin
        server 477579-web-01 34.239.253.230:80 check
        server 477579-web-02 54.221.182.176:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
